baseURL = "http://www.tahirozdemir.com/"
languageCode = "tr-tr"
title = "Tahir Özdemir"
theme = "hugo-kiera"
pygmentsCodeFences = true
disqusShortname = "tahirozdemir" #Disqus shortname
paginate = 5

[author]
    name = "Tahir Özdemir"           #Author name
    github = "tahirozdemir34"         #Github username
    linkedin = "tahir-özdemir-8902aa188"       #LinkedIn username
    twitter = "tahirzdmr"        #Twitter username
    medium = "tahirozdemir34"
    home = "http://me.tahirozdemir.com"
    resume = "http://cv.tahirozdemir.com"


[permalinks]
  posts = "/:year/:month/:filename/"